### PR TITLE
Fixing assignment operators for slices to accept matrices with any storage order

### LINKED ISSUE #4: Assignment operator of rowslice
I am calculating the outer product of a 1-D and a 2-D array:
```C++
    blaze::DynamicMatrix<int> m{{42, 1, 1}, {4, 5, 6}};
    blaze::DynamicVector<int> v{1, 2};
    blaze::DynamicTensor<int> result(v.size(), m.rows(), m.columns(),-10);
    for (std::size_t i=0; i!=m.rows();++i)
    {
        auto slice = blaze::rowslice(result, i);
        slice = blaze::trans(blaze::outer(v, blaze::row(m, i)));
    }
```
while the code in the above block works, I like to change the order of arrays in `blaze::outer` so I would get rid of the extra `trans`:
```C++
    for (std::size_t i=0; i!=m.rows();++i)
    {
        auto slice = blaze::rowslice(result, i);
        slice = blaze::outer(blaze::row(m, i), v);;
    }
```
```log
binary '=': no operator found which takes a right-hand operand of type 'ReturnType' (or there is no acceptable conversion)
```

### PR DESCRIPTION
**Pull request by hkaiser**
Fixes #4

### CODE REVIEW

**Comment by hkaiser** [comment]
@taless474 please check if this fixes your issue.

**Comment by taless474** [comment]
Thank you for the effort. Now I get this error:
```console
1>c:\repos\blaze_tensor\blaze_tensor\math\views\rowslice\dense.h(822): error C2338: Non-column-major matrix type detected
1>c:\repos\blaze_app_1\prog.cpp(1082): note: see reference to function template instantiation 'blaze::RowSlice<MT> &blaze::RowSlice<MT>::operator =<blaze::DVecDVecOuterExpr<VT1,VT2>,false>(const blaze::Matrix<blaze::DVecDVecOuterExpr<VT1,VT2>,false> &)' being compiled
1>        with
1>        [
1>            MT=blaze::DynamicTensor<int>,
1>            VT1=blaze::DVecTransExpr<blaze::Row<blaze::DynamicMatrix<int,false>,true,true,false>,false>,
1>            VT2=blaze::DVecTransExpr<blaze::DynamicVector<int,false>,true>
1>        ]
1>c:\repos\blaze_app_1\prog.cpp(1082): note: see reference to function template instantiation 'blaze::RowSlice<MT> &blaze::RowSlice<MT>::operator =<blaze::DVecDVecOuterExpr<VT1,VT2>,false>(const blaze::Matrix<blaze::DVecDVecOuterExpr<VT1,VT2>,false> &)' being compiled
1>        with
1>        [
1>            MT=blaze::DynamicTensor<int>,
1>            VT1=blaze::DVecTransExpr<blaze::Row<blaze::DynamicMatrix<int,false>,true,true,false>,false>,
1>            VT2=blaze::DVecTransExpr<blaze::DynamicVector<int,false>,true>
1>        ]
1>c:\repos\vcpkg\installed\x64-windows\include\blaze\math\views\check.h(138): note: see reference to class template instantiation 'blaze::Check<false>' being compiled
1>c:\repos\vcpkg\installed\x64-windows\include\blaze\math\views\check.h(121): note: see reference to class template instantiation 'blaze::Check<true>' being compiled
1>c:\repos\hpx\hpx\parallel\execution_policy.hpp(648): note: see reference to class template instantiation 'hpx::parallel::execution::parallel_policy_executor<hpx::launch>' being compiled
```

**Comment by hkaiser** [comment]
@taless474 should be fine now.

**Comment by taless474** [comment]
It is, thanks.

**Pull request merged**
