### PR TITLE
Fixing reduction of arrays

### LINKED ISSUE #44: nD Reduce Map always returns false
The following code:
```c++
	struct isSame
    {
        bool operator()(double lhs, double rhs) const
        {
			return lhs == rhs;
        }
    };

    blaze::DynamicArray<4UL, int> q{{{{{-5, -3, -1, -2, 0}}}}};
    blaze::DynamicTensor<int> t{{{-5, -3, -1, -2, 0}}};
    std::cout<<blaze::reduce(blaze::map(q, q, isSame{}), std::logical_and<bool>{})<<"\n";
    std::cout<<blaze::reduce(blaze::map(t, t, isSame{}), std::logical_and<bool>{})<<"\n";
```
would print:
```console
0
1
```

### PR DESCRIPTION
**Pull request by hkaiser**
Fixes #44

### CODE REVIEW

**Comment by taless474** [comment]
I get `'data': is not a member of 'blaze::DArrDArrMapExpr<MT1,MT2,OP>'`compiling Phylanx's 4d_softmax.
```console
1>c:\repos\blaze_tensor\blaze_tensor\math\expressions\darrreduceexpr.h(963): error C2039: 'data': is not a member of 'blaze::DArrDArrMapExpr<MT1,MT2,OP>'
1>        with
1>        [
1>            MT1=blaze::CustomArray<4,double,true,true,blaze::DynamicArray<4,double>>,
1>            MT2=blaze::CustomArray<4,double,true,true,blaze::DynamicArray<4,double>>,
1>            OP=phylanx::ir::detail::isclose
1>        ]
1>c:\repos\blaze_tensor\blaze_tensor\math\expressions\darrdarrmapexpr.h(932): note: see declaration of 'blaze::DArrDArrMapExpr<MT1,MT2,OP>'
1>        with
1>        [
1>            MT1=blaze::CustomArray<4,double,true,true,blaze::DynamicArray<4,double>>,
1>            MT2=blaze::CustomArray<4,double,true,true,blaze::DynamicArray<4,double>>,
1>            OP=phylanx::ir::detail::isclose
1>        ]
1>c:\repos\blaze_tensor\blaze_tensor\math\expressions\darrreduceexpr.h(1011): note: see reference to function template instantiation 'bool blaze::darrayreduce<blaze::DArrDArrMapExpr<MT1,MT2,OP>,std::logical_and<bool>>(const blaze::DenseArray<blaze::DArrDArrMapExpr<MT1,MT2,OP>> &,std::logical_and<bool>)' being compiled
1>        with
1>        [
1>            MT1=blaze::CustomArray<4,double,true,true,blaze::DynamicArray<4,double>>,
1>            MT2=blaze::CustomArray<4,double,true,true,blaze::DynamicArray<4,double>>,
1>            OP=phylanx::ir::detail::isclose
1>        ]
1>c:\repos\phylanx\src\ir\node_data.cpp(2717): note: see reference to function template instantiation 'bool blaze::reduce<blaze::DArrDArrMapExpr<MT1,MT2,OP>,std::logical_and<bool>>(const blaze::DenseArray<blaze::DArrDArrMapExpr<MT1,MT2,OP>> &,std::logical_and<bool>)' being compiled
1>        with
1>        [
1>            MT1=blaze::CustomArray<4,double,true,true,blaze::DynamicArray<4,double>>,
1>            MT2=blaze::CustomArray<4,double,true,true,blaze::DynamicArray<4,double>>,
1>            OP=phylanx::ir::detail::isclose
1>        ]
1>c:\repos\hpx\libs\parallel_executors\include\hpx\parallel\execution_policy.hpp(648): note: see reference to class template instantiation 'hpx::parallel::execution::parallel_policy_executor<hpx::launch>' being compiled
```

**Comment by hkaiser** [comment]
Grrr...

**Comment by hkaiser** [comment]
@taless474 Better now?

**Comment by taless474** [comment]
Yes, thank you :)

**Pull request merged**
